-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.activities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  source text NOT NULL CHECK (source = ANY (ARRAY['strava'::text, 'garmin'::text, 'manual'::text, 'apple'::text, 'fitbit'::text, 'polar'::text, 'suunto'::text, 'wahoo'::text, 'quick_entry'::text, 'workout_log'::text])),
  external_id text,
  name text NOT NULL,
  activity_type text NOT NULL,
  sport_type text,
  start_date timestamp with time zone NOT NULL,
  end_date timestamp with time zone,
  timezone text,
  utc_offset integer,
  elapsed_time_seconds integer NOT NULL,
  moving_time_seconds integer,
  distance_meters numeric,
  average_speed numeric,
  max_speed numeric,
  total_elevation_gain numeric,
  total_elevation_loss numeric,
  elevation_high numeric,
  elevation_low numeric,
  average_heartrate integer,
  max_heartrate integer,
  min_heartrate integer,
  heartrate_zones jsonb,
  average_power numeric,
  max_power integer,
  normalized_power numeric,
  intensity_factor numeric,
  tss numeric,
  power_zones jsonb,
  kilojoules numeric,
  average_cadence numeric,
  max_cadence integer,
  average_stride_length numeric,
  average_vertical_oscillation numeric,
  average_ground_contact_time integer,
  average_ground_contact_balance numeric,
  average_vertical_ratio numeric,
  pool_length numeric,
  total_strokes integer,
  average_stroke_rate numeric,
  average_swolf numeric,
  lap_count integer,
  total_reps integer,
  total_sets integer,
  total_weight_lifted_kg numeric,
  exercise_count integer,
  muscle_groups ARRAY,
  total_shots integer,
  forehand_count integer,
  backhand_count integer,
  serve_count integer,
  volley_count integer,
  winner_count integer,
  unforced_error_count integer,
  ace_count integer,
  double_fault_count integer,
  first_serve_percentage numeric,
  points_won_percentage numeric,
  match_duration_minutes integer,
  sets_played integer,
  games_played integer,
  average_distance_per_stroke numeric,
  average_split_time integer,
  poses_held integer,
  average_hold_duration integer,
  flexibility_score integer,
  calories integer,
  active_calories integer,
  training_load numeric,
  aerobic_training_effect numeric,
  anaerobic_training_effect numeric,
  recovery_time_hours integer,
  vo2max_estimate numeric,
  fitness_level integer,
  perceived_exertion integer CHECK (perceived_exertion >= 1 AND perceived_exertion <= 10),
  mood text CHECK (mood = ANY (ARRAY['terrible'::text, 'bad'::text, 'okay'::text, 'good'::text, 'amazing'::text])),
  energy_level integer CHECK (energy_level >= 1 AND energy_level <= 5),
  soreness_level integer CHECK (soreness_level >= 0 AND soreness_level <= 10),
  stress_level integer CHECK (stress_level >= 0 AND stress_level <= 10),
  sleep_quality integer CHECK (sleep_quality >= 1 AND sleep_quality <= 10),
  workout_rating integer CHECK (workout_rating >= 1 AND workout_rating <= 5),
  weather_conditions text,
  temperature_celsius numeric,
  humidity_percentage integer,
  wind_speed_kmh numeric,
  wind_direction integer,
  precipitation text,
  air_quality_index integer,
  indoor boolean DEFAULT false,
  gear_id text,
  location text,
  route_name text,
  city text,
  state text,
  country text,
  start_lat numeric,
  start_lng numeric,
  end_lat numeric,
  end_lng numeric,
  workout_id integer,
  notes text,
  private_notes text,
  photos ARRAY,
  videos ARRAY,
  map_polyline text,
  kudos_count integer DEFAULT 0,
  comment_count integer DEFAULT 0,
  photo_count integer DEFAULT 0,
  visibility text DEFAULT 'private'::text CHECK (visibility = ANY (ARRAY['private'::text, 'followers'::text, 'public'::text])),
  commute boolean DEFAULT false,
  trainer boolean DEFAULT false,
  race boolean DEFAULT false,
  workout_type text,
  weather_data jsonb,
  raw_data jsonb,
  laps jsonb,
  splits jsonb,
  segments jsonb,
  device_name text,
  device_manufacturer text,
  upload_source text,
  file_format text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  synced_at timestamp with time zone,
  performance_score numeric CHECK (performance_score >= 0::numeric AND performance_score <= 10::numeric),
  effort_level numeric CHECK (effort_level >= 0::numeric AND effort_level <= 10::numeric),
  recovery_needed_hours integer,
  tags ARRAY DEFAULT ARRAY[]::text[],
  activity_name text,
  duration_minutes integer,
  rpe integer CHECK (rpe >= 1 AND rpe <= 10),
  energy_level_before integer CHECK (energy_level_before >= 1 AND energy_level_before <= 10),
  energy_level_after integer CHECK (energy_level_after >= 1 AND energy_level_after <= 10),
  completed boolean DEFAULT true,
  quick_entry_log_id uuid,
  ai_extracted boolean DEFAULT false,
  ai_confidence numeric CHECK (ai_confidence >= 0::numeric AND ai_confidence <= 1::numeric),
  extraction_metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT activities_pkey PRIMARY KEY (id),
  CONSTRAINT activities_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT activities_quick_entry_log_id_fkey FOREIGN KEY (quick_entry_log_id) REFERENCES public.quick_entry_logs(id)
);
CREATE TABLE public.activity_exercises (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  activity_id uuid NOT NULL,
  exercise_id uuid,
  workout_exercise_id uuid,
  order_index integer,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT activity_exercises_pkey PRIMARY KEY (id),
  CONSTRAINT activity_exercises_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES public.activities(id),
  CONSTRAINT activity_exercises_workout_exercise_id_fkey FOREIGN KEY (workout_exercise_id) REFERENCES public.workout_exercises(id)
);
CREATE TABLE public.activity_segments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  activity_id uuid,
  segment_type text NOT NULL CHECK (segment_type = ANY (ARRAY['lap'::text, 'interval'::text, 'set'::text, 'split'::text, 'circuit'::text, 'round'::text])),
  segment_index integer NOT NULL,
  start_time timestamp with time zone,
  elapsed_time_seconds integer,
  moving_time_seconds integer,
  distance_meters numeric,
  average_speed numeric,
  max_speed numeric,
  average_pace text,
  average_heartrate integer,
  max_heartrate integer,
  min_heartrate integer,
  exercise_name text,
  reps integer,
  weight_kg numeric,
  average_cadence numeric,
  average_power numeric,
  normalized_power numeric,
  calories integer,
  elevation_gain numeric,
  elevation_loss numeric,
  average_stroke_rate numeric,
  stroke_count integer,
  notes text,
  raw_data jsonb,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT activity_segments_pkey PRIMARY KEY (id),
  CONSTRAINT activity_segments_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES public.activities(id)
);
CREATE TABLE public.activity_sets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  activity_exercise_id uuid NOT NULL,
  set_number integer NOT NULL,
  reps_completed integer,
  weight_lbs numeric,
  weight_kg numeric,
  rpe integer CHECK (rpe >= 1 AND rpe <= 10),
  rest_seconds integer,
  completed boolean DEFAULT true,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT activity_sets_pkey PRIMARY KEY (id),
  CONSTRAINT activity_sets_activity_exercise_id_fkey FOREIGN KEY (activity_exercise_id) REFERENCES public.activity_exercises(id)
);
CREATE TABLE public.activity_streams (
  activity_id uuid NOT NULL,
  stream_type text NOT NULL CHECK (stream_type = ANY (ARRAY['heartrate'::text, 'cadence'::text, 'power'::text, 'speed'::text, 'altitude'::text, 'distance'::text, 'temperature'::text, 'grade'::text, 'battery'::text, 'calories'::text, 'lap_time'::text, 'moving'::text])),
  data_points jsonb NOT NULL,
  data_type text CHECK (data_type = ANY (ARRAY['integer'::text, 'float'::text, 'boolean'::text, 'string'::text])),
  resolution text CHECK (resolution = ANY (ARRAY['high'::text, 'medium'::text, 'low'::text, 'raw'::text])),
  original_size integer,
  series_type text CHECK (series_type = ANY (ARRAY['time'::text, 'distance'::text])),
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  CONSTRAINT activity_streams_pkey PRIMARY KEY (activity_id, stream_type),
  CONSTRAINT activity_streams_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES public.activities(id)
);
CREATE TABLE public.ai_conversations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  messages jsonb NOT NULL DEFAULT '[]'::jsonb,
  embedding USER-DEFINED,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  context_used jsonb DEFAULT '{}'::jsonb,
  last_message_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_conversations_pkey PRIMARY KEY (id),
  CONSTRAINT ai_conversations_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.ai_generated_programs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  goals ARRAY,
  duration_weeks integer NOT NULL DEFAULT 12,
  total_days integer NOT NULL DEFAULT 84,
  start_date date,
  end_date date,
  is_active boolean DEFAULT true,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'completed'::text, 'paused'::text, 'abandoned'::text])),
  generation_prompt text,
  generation_context jsonb DEFAULT '{}'::jsonb,
  questions_answers jsonb DEFAULT '[]'::jsonb,
  ai_model text DEFAULT 'gpt-4o'::text,
  difficulty_level text CHECK (difficulty_level = ANY (ARRAY['beginner'::text, 'intermediate'::text, 'advanced'::text])),
  primary_focus ARRAY,
  equipment_needed ARRAY,
  dietary_approach text,
  current_day integer DEFAULT 1,
  days_completed integer DEFAULT 0,
  meals_completed integer DEFAULT 0,
  workouts_completed integer DEFAULT 0,
  adherence_percentage numeric DEFAULT 100 CHECK (adherence_percentage >= 0::numeric AND adherence_percentage <= 100::numeric),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  CONSTRAINT ai_generated_programs_pkey PRIMARY KEY (id),
  CONSTRAINT ai_generated_programs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.ai_program_days (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  program_id uuid NOT NULL,
  day_number integer NOT NULL CHECK (day_number >= 1 AND day_number <= 365),
  day_date date,
  day_of_week text CHECK (day_of_week = ANY (ARRAY['monday'::text, 'tuesday'::text, 'wednesday'::text, 'thursday'::text, 'friday'::text, 'saturday'::text, 'sunday'::text])),
  day_name text,
  day_focus text,
  day_notes text,
  is_completed boolean DEFAULT false,
  completed_at timestamp with time zone,
  completion_notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_program_days_pkey PRIMARY KEY (id),
  CONSTRAINT ai_program_days_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.ai_generated_programs(id)
);
CREATE TABLE public.ai_program_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  program_id uuid NOT NULL,
  program_day_id uuid NOT NULL,
  item_type text NOT NULL CHECK (item_type = ANY (ARRAY['meal'::text, 'workout'::text, 'rest'::text, 'note'::text])),
  item_order integer DEFAULT 0,
  meal_type text CHECK (meal_type = ANY (ARRAY['breakfast'::text, 'lunch'::text, 'dinner'::text, 'snack'::text, 'pre_workout'::text, 'post_workout'::text])),
  meal_name text,
  meal_foods jsonb DEFAULT '[]'::jsonb,
  meal_recipe text,
  meal_calories numeric,
  meal_protein_g numeric,
  meal_carbs_g numeric,
  meal_fat_g numeric,
  workout_name text,
  workout_type text CHECK (workout_type = ANY (ARRAY['strength'::text, 'cardio'::text, 'sports'::text, 'flexibility'::text, 'mobility'::text, 'active_recovery'::text])),
  workout_duration_minutes integer,
  workout_exercises jsonb DEFAULT '[]'::jsonb,
  workout_intensity text CHECK (workout_intensity = ANY (ARRAY['low'::text, 'moderate'::text, 'high'::text, 'max'::text])),
  workout_notes text,
  description text,
  notes text,
  alternatives jsonb,
  is_completed boolean DEFAULT false,
  completed_at timestamp with time zone,
  completion_notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_program_items_pkey PRIMARY KEY (id),
  CONSTRAINT ai_program_items_program_id_fkey FOREIGN KEY (program_id) REFERENCES public.ai_generated_programs(id),
  CONSTRAINT ai_program_items_program_day_id_fkey FOREIGN KEY (program_day_id) REFERENCES public.ai_program_days(id)
);
CREATE TABLE public.body_measurements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  measured_at timestamp with time zone NOT NULL DEFAULT now(),
  weight_lbs numeric,
  weight_kg numeric,
  body_fat_pct numeric,
  muscle_mass_lbs numeric,
  muscle_mass_kg numeric,
  measurements jsonb,
  source text DEFAULT 'manual'::text CHECK (source = ANY (ARRAY['manual'::text, 'scale'::text, 'dexa'::text, 'inbody'::text, 'quick_entry'::text])),
  notes text,
  trend_direction text CHECK (trend_direction = ANY (ARRAY['up'::text, 'down'::text, 'stable'::text])),
  rate_of_change_weekly numeric,
  goal_progress_pct numeric CHECK (goal_progress_pct >= 0::numeric AND goal_progress_pct <= 100::numeric),
  health_assessment text CHECK (health_assessment = ANY (ARRAY['healthy'::text, 'caution'::text, 'concern'::text])),
  tags ARRAY DEFAULT ARRAY[]::text[],
  created_at timestamp with time zone DEFAULT now(),
  quick_entry_log_id uuid,
  ai_extracted boolean DEFAULT false,
  ai_confidence numeric CHECK (ai_confidence >= 0::numeric AND ai_confidence <= 1::numeric),
  extraction_metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT body_measurements_pkey PRIMARY KEY (id),
  CONSTRAINT body_measurements_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT body_measurements_quick_entry_log_id_fkey FOREIGN KEY (quick_entry_log_id) REFERENCES public.quick_entry_logs(id)
);
CREATE TABLE public.coach_conversations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  title text,
  message_count integer DEFAULT 0 CHECK (message_count >= 0),
  archived boolean DEFAULT false,
  last_message_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT coach_conversations_pkey PRIMARY KEY (id),
  CONSTRAINT coach_conversations_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.coach_message_embeddings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  message_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role text NOT NULL CHECK (role = ANY (ARRAY['user'::text, 'assistant'::text, 'system'::text])),
  embedding USER-DEFINED NOT NULL,
  content_text text NOT NULL,
  embedding_model text NOT NULL DEFAULT 'sentence-transformers/all-MiniLM-L6-v2'::text,
  embedding_dimensions integer NOT NULL DEFAULT 384,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT coach_message_embeddings_pkey PRIMARY KEY (id),
  CONSTRAINT coach_message_embeddings_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.coach_messages(id),
  CONSTRAINT coach_message_embeddings_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.coach_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  conversation_id uuid NOT NULL,
  role text NOT NULL CHECK (role = ANY (ARRAY['user'::text, 'assistant'::text, 'system'::text])),
  content text NOT NULL,
  context_used jsonb,
  ai_provider text CHECK (ai_provider = ANY (ARRAY['anthropic'::text, 'groq'::text, 'openai'::text, 'openrouter'::text])),
  ai_model text,
  tokens_used integer,
  cost_usd numeric,
  created_at timestamp with time zone DEFAULT now(),
  message_type text NOT NULL DEFAULT 'chat'::text CHECK (message_type = ANY (ARRAY['chat'::text, 'log_preview'::text, 'log_confirmed'::text, 'system'::text])),
  metadata jsonb DEFAULT '{}'::jsonb,
  quick_entry_log_id uuid,
  is_vectorized boolean DEFAULT false,
  CONSTRAINT coach_messages_pkey PRIMARY KEY (id),
  CONSTRAINT coach_messages_quick_entry_log_id_fkey FOREIGN KEY (quick_entry_log_id) REFERENCES public.quick_entry_logs(id),
  CONSTRAINT coach_messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.coach_conversations(id),
  CONSTRAINT coach_messages_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.daily_nutrition_summaries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  date date NOT NULL,
  total_calories numeric,
  total_protein_g numeric,
  total_carbs_g numeric,
  total_fat_g numeric,
  total_fiber_g numeric,
  total_sugar_g numeric,
  total_sodium_mg numeric,
  breakfast_calories numeric,
  lunch_calories numeric,
  dinner_calories numeric,
  snacks_calories numeric,
  calorie_goal numeric,
  protein_goal numeric,
  carbs_goal numeric,
  fat_goal numeric,
  meals_logged integer DEFAULT 0,
  water_ml numeric,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT daily_nutrition_summaries_pkey PRIMARY KEY (id),
  CONSTRAINT daily_nutrition_summaries_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.foods_enhanced (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  brand_name text,
  brand_owner text,
  restaurant_name text,
  menu_item_id text,
  product_category text,
  food_group text,
  barcode_upc text UNIQUE,
  barcode_ean text UNIQUE,
  fdc_id text UNIQUE,
  fatsecret_id text,
  nutritionix_id text,
  edamam_id text,
  ndb_number text,
  primary_source_id uuid,
  data_sources jsonb DEFAULT '[]'::jsonb,
  data_quality_score numeric CHECK (data_quality_score >= 0::numeric AND data_quality_score <= 1::numeric),
  is_verified boolean DEFAULT false,
  verification_date timestamp with time zone,
  serving_size numeric NOT NULL DEFAULT 100,
  serving_unit text NOT NULL DEFAULT 'g'::text,
  serving_description text,
  servings_per_container numeric,
  household_serving_size text,
  household_serving_unit text,
  calories numeric,
  total_fat_g numeric,
  saturated_fat_g numeric,
  trans_fat_g numeric,
  polyunsaturated_fat_g numeric,
  monounsaturated_fat_g numeric,
  cholesterol_mg numeric,
  sodium_mg numeric,
  total_carbs_g numeric,
  dietary_fiber_g numeric,
  soluble_fiber_g numeric,
  insoluble_fiber_g numeric,
  total_sugars_g numeric,
  added_sugars_g numeric,
  sugar_alcohols_g numeric,
  protein_g numeric,
  vitamin_a_iu numeric,
  vitamin_a_mcg numeric,
  vitamin_c_mg numeric,
  vitamin_d_mcg numeric,
  vitamin_d_iu numeric,
  vitamin_e_mg numeric,
  vitamin_k_mcg numeric,
  thiamin_mg numeric,
  riboflavin_mg numeric,
  niacin_mg numeric,
  vitamin_b6_mg numeric,
  folate_mcg numeric,
  vitamin_b12_mcg numeric,
  biotin_mcg numeric,
  pantothenic_acid_mg numeric,
  choline_mg numeric,
  calcium_mg numeric,
  iron_mg numeric,
  magnesium_mg numeric,
  phosphorus_mg numeric,
  potassium_mg numeric,
  zinc_mg numeric,
  copper_mg numeric,
  manganese_mg numeric,
  selenium_mcg numeric,
  iodine_mcg numeric,
  caffeine_mg numeric,
  alcohol_g numeric,
  water_g numeric,
  ash_g numeric,
  omega3_fatty_acids_mg numeric,
  omega6_fatty_acids_mg numeric,
  search_vector tsvector,
  popularity_score integer DEFAULT 0,
  search_count integer DEFAULT 0,
  ingredients ARRAY,
  allergens ARRAY,
  dietary_flags ARRAY,
  preparation_methods ARRAY,
  storage_instructions text,
  image_url text,
  image_thumbnail_url text,
  nutrition_label_url text,
  is_discontinued boolean DEFAULT false,
  is_generic boolean DEFAULT false,
  is_raw boolean DEFAULT false,
  is_branded boolean DEFAULT false,
  is_restaurant boolean DEFAULT false,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_api_sync timestamp with time zone,
  CONSTRAINT foods_enhanced_pkey PRIMARY KEY (id),
  CONSTRAINT foods_enhanced_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.integrations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  provider text NOT NULL CHECK (provider = ANY (ARRAY['strava'::text, 'garmin'::text, 'apple_health'::text, 'google_fit'::text, 'fitbit'::text, 'polar'::text, 'whoop'::text])),
  is_active boolean DEFAULT true,
  connected_at timestamp with time zone DEFAULT now(),
  last_sync_at timestamp with time zone,
  sync_enabled boolean DEFAULT true,
  provider_user_id text,
  provider_email text,
  access_token text,
  refresh_token text,
  token_expires_at timestamp with time zone,
  scope text,
  sync_settings jsonb DEFAULT '{"sync_hr": true, "auto_sync": true, "sync_sleep": false, "sync_activities": true}'::jsonb,
  last_sync_status text CHECK (last_sync_status = ANY (ARRAY['success'::text, 'failed'::text, 'partial'::text])),
  last_sync_error text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT integrations_pkey PRIMARY KEY (id),
  CONSTRAINT integrations_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.meal_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  name text CHECK (name IS NULL OR char_length(name) <= 200),
  category USER-DEFINED NOT NULL DEFAULT 'other'::meal_category,
  logged_at timestamp with time zone NOT NULL DEFAULT now(),
  notes text CHECK (notes IS NULL OR char_length(notes) <= 500),
  total_calories numeric DEFAULT 0,
  total_protein_g numeric DEFAULT 0,
  total_carbs_g numeric DEFAULT 0,
  total_fat_g numeric DEFAULT 0,
  total_fiber_g numeric DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  foods jsonb DEFAULT '[]'::jsonb,
  source text DEFAULT 'manual'::text CHECK (source = ANY (ARRAY['quick_entry'::text, 'manual'::text, 'imported'::text, 'api'::text])),
  estimated boolean DEFAULT false,
  confidence_score numeric CHECK (confidence_score >= 0::numeric AND confidence_score <= 1::numeric),
  image_url text,
  meal_quality_score numeric CHECK (meal_quality_score >= 0::numeric AND meal_quality_score <= 10::numeric),
  macro_balance_score numeric CHECK (macro_balance_score >= 0::numeric AND macro_balance_score <= 10::numeric),
  adherence_to_goals numeric CHECK (adherence_to_goals >= 0::numeric AND adherence_to_goals <= 10::numeric),
  tags ARRAY DEFAULT ARRAY[]::text[],
  total_sugar_g numeric,
  total_sodium_mg numeric,
  quick_entry_log_id uuid,
  ai_extracted boolean DEFAULT false,
  ai_confidence numeric CHECK (ai_confidence >= 0::numeric AND ai_confidence <= 1::numeric),
  extraction_metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT meal_logs_pkey PRIMARY KEY (id),
  CONSTRAINT meal_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT meal_logs_quick_entry_log_id_fkey FOREIGN KEY (quick_entry_log_id) REFERENCES public.quick_entry_logs(id)
);
CREATE TABLE public.multimodal_embeddings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  data_type text NOT NULL CHECK (data_type = ANY (ARRAY['text'::text, 'image'::text, 'audio'::text, 'video'::text, 'pdf'::text, 'structured'::text, 'mixed'::text])),
  content_text text,
  embedding USER-DEFINED NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb,
  source_type text NOT NULL CHECK (source_type = ANY (ARRAY['meal'::text, 'meal_log'::text, 'meal_photo'::text, 'workout'::text, 'workout_log'::text, 'workout_photo'::text, 'workout_video'::text, 'activity'::text, 'activity_photo'::text, 'activity_gpx'::text, 'goal'::text, 'user_goal'::text, 'profile'::text, 'user_profile'::text, 'coach_message'::text, 'conversation'::text, 'program'::text, 'ai_program'::text, 'voice_note'::text, 'quick_entry'::text, 'food_label'::text, 'nutrition_label'::text, 'body_photo'::text, 'progress_photo'::text, 'other'::text])),
  source_id uuid,
  storage_url text,
  storage_bucket text CHECK (storage_bucket = ANY (ARRAY['user-images'::text, 'user-audio'::text, 'user-videos'::text, 'user-documents'::text, 'user-photos'::text])),
  file_name text,
  file_size_bytes bigint,
  mime_type text,
  embedding_model text NOT NULL DEFAULT 'all-MiniLM-L6-v2'::text,
  embedding_dimensions integer NOT NULL DEFAULT 384,
  confidence_score numeric CHECK (confidence_score >= 0::numeric AND confidence_score <= 1::numeric),
  processing_status text DEFAULT 'completed'::text CHECK (processing_status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'failed'::text])),
  processing_error text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT multimodal_embeddings_pkey PRIMARY KEY (id),
  CONSTRAINT multimodal_embeddings_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  full_name text,
  goal text CHECK (goal = ANY (ARRAY['build_muscle'::text, 'lose_weight'::text, 'gain_strength'::text])),
  onboarding_completed boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  goals_embedding USER-DEFINED,
  about_me text,
  experience_level USER-DEFINED DEFAULT 'beginner'::experience_level,
  fitness_goals text,
  preferred_activities ARRAY,
  motivation_factors ARRAY,
  physical_limitations ARRAY,
  available_equipment ARRAY,
  training_frequency text,
  session_duration text,
  dietary_preferences text,
  notification_preferences jsonb DEFAULT '{}'::jsonb,
  privacy_settings jsonb DEFAULT '{}'::jsonb,
  age integer CHECK (age >= 13 AND age <= 120),
  location text,
  weekly_hours numeric CHECK (weekly_hours >= 0::numeric AND weekly_hours <= 40::numeric),
  primary_goal text,
  focus_areas ARRAY,
  health_conditions text,
  equipment_access text,
  preferred_workout_time text,
  strengths text,
  areas_for_improvement text,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.quick_entry_embeddings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  quick_entry_log_id uuid NOT NULL,
  user_id uuid NOT NULL,
  embedding_type text NOT NULL CHECK (embedding_type = ANY (ARRAY['text'::text, 'image'::text, 'audio'::text, 'multimodal'::text, 'combined'::text])),
  embedding USER-DEFINED NOT NULL,
  content_text text NOT NULL,
  content_summary text,
  metadata jsonb DEFAULT '{}'::jsonb,
  source_classification text,
  embedding_model text NOT NULL DEFAULT 'sentence-transformers/all-MiniLM-L6-v2'::text,
  embedding_dimensions integer NOT NULL DEFAULT 384,
  content_hash text NOT NULL,
  is_active boolean DEFAULT true,
  logged_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT quick_entry_embeddings_pkey PRIMARY KEY (id),
  CONSTRAINT quick_entry_embeddings_quick_entry_log_id_fkey FOREIGN KEY (quick_entry_log_id) REFERENCES public.quick_entry_logs(id),
  CONSTRAINT quick_entry_embeddings_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.quick_entry_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  input_type text NOT NULL CHECK (input_type = ANY (ARRAY['text'::text, 'voice'::text, 'image'::text, 'multimodal'::text, 'pdf'::text])),
  input_modalities ARRAY NOT NULL DEFAULT ARRAY[]::text[],
  raw_text text,
  raw_transcription text,
  image_urls ARRAY DEFAULT ARRAY[]::text[],
  audio_url text,
  pdf_url text,
  storage_bucket text CHECK (storage_bucket = ANY (ARRAY['user-images'::text, 'user-audio'::text, 'user-videos'::text, 'user-documents'::text])),
  file_metadata jsonb DEFAULT '{}'::jsonb,
  ai_provider text NOT NULL CHECK (ai_provider = ANY (ARRAY['groq'::text, 'openrouter'::text, 'anthropic'::text, 'openai'::text, 'local'::text, 'free'::text])),
  ai_model text NOT NULL,
  ai_cost_usd numeric DEFAULT 0,
  tokens_used integer DEFAULT 0,
  processing_duration_ms integer,
  ai_classification text CHECK (ai_classification = ANY (ARRAY['meal'::text, 'workout'::text, 'body_measurement'::text, 'activity'::text, 'goal'::text, 'note'::text, 'mixed'::text, 'unknown'::text])),
  ai_extracted_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  ai_confidence_score numeric CHECK (ai_confidence_score >= 0::numeric AND ai_confidence_score <= 1::numeric),
  ai_raw_response text,
  contains_meal boolean DEFAULT false,
  contains_workout boolean DEFAULT false,
  contains_body_measurement boolean DEFAULT false,
  contains_activity boolean DEFAULT false,
  contains_goal boolean DEFAULT false,
  contains_note boolean DEFAULT false,
  meal_log_ids ARRAY DEFAULT ARRAY[]::uuid[],
  workout_log_ids ARRAY DEFAULT ARRAY[]::uuid[],
  body_measurement_ids ARRAY DEFAULT ARRAY[]::uuid[],
  activity_ids ARRAY DEFAULT ARRAY[]::uuid[],
  logged_at timestamp with time zone NOT NULL DEFAULT now(),
  timezone text DEFAULT 'UTC'::text,
  location_lat numeric,
  location_lng numeric,
  processing_status text NOT NULL DEFAULT 'pending'::text CHECK (processing_status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'failed'::text, 'partial'::text])),
  processing_error text,
  retry_count integer DEFAULT 0,
  embedding_generated boolean DEFAULT false,
  embedding_id uuid,
  auto_tags ARRAY DEFAULT ARRAY[]::text[],
  user_tags ARRAY DEFAULT ARRAY[]::text[],
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT quick_entry_logs_pkey PRIMARY KEY (id),
  CONSTRAINT quick_entry_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.quick_entry_stats (
  user_id uuid NOT NULL,
  total_entries integer DEFAULT 0,
  text_entries integer DEFAULT 0,
  voice_entries integer DEFAULT 0,
  image_entries integer DEFAULT 0,
  multimodal_entries integer DEFAULT 0,
  meal_extractions integer DEFAULT 0,
  workout_extractions integer DEFAULT 0,
  body_measurement_extractions integer DEFAULT 0,
  failed_extractions integer DEFAULT 0,
  total_ai_cost_usd numeric DEFAULT 0,
  total_tokens_used bigint DEFAULT 0,
  avg_processing_time_ms integer,
  avg_confidence_score numeric,
  first_entry_at timestamp with time zone,
  last_entry_at timestamp with time zone,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT quick_entry_stats_pkey PRIMARY KEY (user_id),
  CONSTRAINT quick_entry_stats_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.rate_limits (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  endpoint text NOT NULL,
  requests integer DEFAULT 0,
  window_seconds integer DEFAULT 86400,
  reset_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT rate_limits_pkey PRIMARY KEY (id),
  CONSTRAINT rate_limits_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_goals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  goal_type USER-DEFINED NOT NULL,
  goal_description text NOT NULL,
  target_value numeric,
  target_unit text,
  target_date date,
  priority integer DEFAULT 1 CHECK (priority >= 1 AND priority <= 5),
  status USER-DEFINED DEFAULT 'active'::goal_status,
  is_active boolean DEFAULT true,
  progress_value numeric DEFAULT 0,
  progress_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  CONSTRAINT user_goals_pkey PRIMARY KEY (id),
  CONSTRAINT user_goals_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_onboarding (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  primary_goal text NOT NULL CHECK (primary_goal = ANY (ARRAY['build_muscle'::text, 'lose_fat'::text, 'improve_endurance'::text, 'increase_strength'::text, 'sport_performance'::text, 'general_health'::text, 'rehab_recovery'::text])),
  user_persona text NOT NULL CHECK (user_persona = ANY (ARRAY['strength_athlete'::text, 'bodybuilder'::text, 'endurance_runner'::text, 'triathlete'::text, 'crossfit_athlete'::text, 'team_sport_athlete'::text, 'general_fitness'::text, 'beginner_recovery'::text])),
  current_activity_level text NOT NULL CHECK (current_activity_level = ANY (ARRAY['sedentary'::text, 'lightly_active'::text, 'moderately_active'::text, 'very_active'::text])),
  desired_training_frequency integer NOT NULL CHECK (desired_training_frequency >= 3 AND desired_training_frequency <= 7),
  biological_sex text NOT NULL CHECK (biological_sex = ANY (ARRAY['male'::text, 'female'::text])),
  age integer NOT NULL CHECK (age >= 18 AND age <= 80),
  current_weight_kg numeric NOT NULL CHECK (current_weight_kg > 0::numeric),
  height_cm numeric NOT NULL CHECK (height_cm > 0::numeric),
  daily_meal_preference integer NOT NULL CHECK (daily_meal_preference = ANY (ARRAY[2, 3, 4, 5, 6])),
  training_time_preferences ARRAY DEFAULT ARRAY[]::text[],
  dietary_restrictions ARRAY DEFAULT ARRAY[]::text[],
  equipment_access ARRAY DEFAULT ARRAY[]::text[],
  injury_limitations ARRAY DEFAULT ARRAY[]::text[],
  experience_level text NOT NULL CHECK (experience_level = ANY (ARRAY['beginner'::text, 'intermediate'::text, 'advanced'::text, 'expert'::text])),
  completed boolean NOT NULL DEFAULT false,
  completed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  city text,
  location_permission boolean DEFAULT false,
  facility_access ARRAY DEFAULT ARRAY[]::text[],
  daily_calorie_target integer,
  daily_protein_target_g integer,
  daily_carbs_target_g integer,
  daily_fat_target_g integer,
  goal_weight_kg numeric,
  goal_body_fat_pct numeric,
  estimated_tdee integer,
  goal_type text CHECK (goal_type = ANY (ARRAY['cut'::text, 'bulk'::text, 'maintain'::text, 'recomp'::text])),
  CONSTRAINT user_onboarding_pkey PRIMARY KEY (id),
  CONSTRAINT user_onboarding_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL,
  full_name text,
  email text UNIQUE,
  age integer CHECK (age >= 13 AND age <= 120),
  biological_sex text CHECK (biological_sex = ANY (ARRAY['male'::text, 'female'::text, 'other'::text])),
  height_cm numeric CHECK (height_cm > 0::numeric AND height_cm < 300::numeric),
  current_weight_kg numeric CHECK (current_weight_kg > 0::numeric AND current_weight_kg < 500::numeric),
  goal_weight_kg numeric,
  primary_goal text CHECK (primary_goal = ANY (ARRAY['build_muscle'::text, 'lose_fat'::text, 'improve_endurance'::text, 'increase_strength'::text, 'sport_performance'::text, 'general_health'::text])),
  experience_level text CHECK (experience_level = ANY (ARRAY['beginner'::text, 'intermediate'::text, 'advanced'::text])),
  training_frequency integer CHECK (training_frequency >= 0 AND training_frequency <= 7),
  available_equipment ARRAY DEFAULT ARRAY[]::text[],
  dietary_restrictions ARRAY DEFAULT ARRAY[]::text[],
  injury_limitations ARRAY DEFAULT ARRAY[]::text[],
  daily_calorie_target integer,
  daily_protein_target_g integer,
  daily_carbs_target_g integer,
  daily_fat_target_g integer,
  settings jsonb DEFAULT '{"privacy": {"share_stats": false, "activities_public": false}, "timezone": "UTC", "unit_system": "metric", "workout_reminders": true, "auto_sync_activities": true, "notifications_enabled": true, "preferred_workout_time": null}'::jsonb,
  onboarding_completed boolean DEFAULT false,
  onboarding_data jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_active_at timestamp with time zone,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.webhook_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  source text NOT NULL,
  event_type text NOT NULL,
  object_type text,
  object_id text,
  athlete_id bigint,
  payload jsonb,
  processed boolean DEFAULT false,
  processed_at timestamp with time zone,
  error text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT webhook_events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.workout_exercises (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  workout_id integer NOT NULL,
  exercise_id uuid,
  order_index integer NOT NULL,
  suggested_sets integer,
  suggested_reps text,
  suggested_weight_type text,
  suggested_weight_percentage numeric,
  suggested_weight_lbs numeric,
  rest_seconds integer,
  notes text,
  technique_cues ARRAY,
  superset_group integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT workout_exercises_pkey PRIMARY KEY (id)
);